// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZgvup4N1bIpVun24gXXIgmWlO8ti4k8c',
    appId: '1:1029364505523:web:8471b9c6b44eba3a3d49c6',
    messagingSenderId: '1029364505523',
    projectId: 'on-your-request',
    authDomain: 'on-your-request.firebaseapp.com',
    storageBucket: 'on-your-request.firebasestorage.app',
    measurementId: 'G-RD3QG57SL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByNuaxYSTHORIeY6VIyk51awxMuP1Bvzc',
    appId: '1:1029364505523:android:c87f5f879a9ece983d49c6',
    messagingSenderId: '1029364505523',
    projectId: 'on-your-request',
    storageBucket: 'on-your-request.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23-YHhnyE7ppGk4RbRse0A90F6yQTNMc',
    appId: '1:1029364505523:ios:b2f8217c5f2772143d49c6',
    messagingSenderId: '1029364505523',
    projectId: 'on-your-request',
    storageBucket: 'on-your-request.firebasestorage.app',
    iosBundleId: 'com.bkhedmtak.bkhedmtak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC23-YHhnyE7ppGk4RbRse0A90F6yQTNMc',
    appId: '1:1029364505523:ios:b2f8217c5f2772143d49c6',
    messagingSenderId: '1029364505523',
    projectId: 'on-your-request',
    storageBucket: 'on-your-request.firebasestorage.app',
    iosBundleId: 'com.bkhedmtak.bkhedmtak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZgvup4N1bIpVun24gXXIgmWlO8ti4k8c',
    appId: '1:1029364505523:web:308be68fb28c20e03d49c6',
    messagingSenderId: '1029364505523',
    projectId: 'on-your-request',
    authDomain: 'on-your-request.firebaseapp.com',
    storageBucket: 'on-your-request.firebasestorage.app',
    measurementId: 'G-4CL0HQ7GCD',
  );
}
